{
    "CreateLinks": [],
    "OnFailure": "/Molinos2/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/Molinos2/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Category": "#Control:Category/#Value",
        "CategoryName": "#Control:CategoryName/#Value",
        "MainCategory": "#Control:MainCategory/#Value",
        "MainCategoryName": "#Control:MainCategoryName/#Value",
        "NumberOfProducts": "#Control:NumberOfProducts/#Value",
        "UpdatedTimestamp": "#Control:UpdatedTimestamp/#Value"
    },
    "Target": {
        "EntitySet": "ProductCategories",
        "Service": "/Molinos2/Services/MolinosTest_v2.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}