{
    "CreateLinks": [],
    "OnFailure": "/Molinos2/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/Molinos2/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "CurrencyCode": "#Control:CurrencyCode/#Value",
        "GrossAmount": "#Control:GrossAmount/#Value",
        "ItemNumber": "#Control:ItemNumber/#Value",
        "NetAmount": "#Control:NetAmount/#Value",
        "ProductId": "#Control:ProductId/#SelectedValue",
        "PurchaseOrderId": "#Control:PurchaseOrderId/#SelectedValue",
        "Quantity": "#Control:Quantity/#Value",
        "QuantityUnit": "#Control:QuantityUnit/#Value",
        "TaxAmount": "#Control:TaxAmount/#Value"
    },
    "Target": {
        "EntitySet": "PurchaseOrderItems",
        "Service": "/Molinos2/Services/MolinosTest_v2.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}